class Instructions:


    instructions = {'0A': {'instruction': 'ASL', 'AMOD': 'A'},
    '06': {'instruction': 'ASL', 'AMOD': 'oper'},
    '16': {'instruction': 'ASL', 'AMOD': 'oper'},
    '0E': {'instruction': 'ASL', 'AMOD': 'oper'},
    '1E': {'instruction': 'ASL', 'AMOD': 'oper'},
    '00': {'instruction': 'BRK', 'AMOD': 'impl'},
    '18': {'instruction': 'CLC', 'AMOD': 'impl'},
    'D8': {'instruction': 'CLD', 'AMOD': 'impl'},
    '58': {'instruction': 'CLI', 'AMOD': 'impl'},
    'B8': {'instruction': 'CLV', 'AMOD': 'impl'},
    'CA': {'instruction': 'DEX', 'AMOD': 'impl'},
    '88': {'instruction': 'DEY', 'AMOD': 'impl'},
    'E8': {'instruction': 'INX', 'AMOD': 'impl'},
    'C8': {'instruction': 'INY', 'AMOD': 'impl'},
    '4A': {'instruction': 'LSR', 'AMOD': 'A'},
    '46': {'instruction': 'LSR', 'AMOD': 'oper'},
    '56': {'instruction': 'LSR', 'AMOD': 'oper'},
    '4E': {'instruction': 'LSR', 'AMOD': 'oper'},
    '5E': {'instruction': 'LSR', 'AMOD': 'oper'},
    'EA': {'instruction': 'NOP', 'AMOD': 'impl'},
    '48': {'instruction': 'PHA', 'AMOD': 'impl'},
    '08': {'instruction': 'PHP', 'AMOD': 'impl'},
    '68': {'instruction': 'PLA', 'AMOD': 'impl'},
    '28': {'instruction': 'PLP', 'AMOD': 'impl'},
    '2A': {'instruction': 'ROL', 'AMOD': 'A'},
    '26': {'instruction': 'ROL', 'AMOD': 'oper'},
    '36': {'instruction': 'ROL', 'AMOD': 'oper'},
    '2E': {'instruction': 'ROL', 'AMOD': 'oper'},
    '3E': {'instruction': 'ROL', 'AMOD': 'oper'},
    '6A': {'instruction': 'ROR', 'AMOD': 'A'},
    '66': {'instruction': 'ROR', 'AMOD': 'oper'},
    '76': {'instruction': 'ROR', 'AMOD': 'oper'},
    '6E': {'instruction': 'ROR', 'AMOD': 'oper'},
    '7E': {'instruction': 'ROR', 'AMOD': 'oper'},
    '38': {'instruction': 'SEC', 'AMOD': 'impl'},
    'F8': {'instruction': 'SED', 'AMOD': 'impl'},
    '78': {'instruction': 'SEI', 'AMOD': 'impl'},
    'AA': {'instruction': 'TAX', 'AMOD': 'impl'},
    'A8': {'instruction': 'TAY', 'AMOD': 'impl'},
    'BA': {'instruction': 'TSX', 'AMOD': 'impl'},
    '8A': {'instruction': 'TXA', 'AMOD': 'impl'},
    '9A': {'instruction': 'TXS', 'AMOD': 'impl'},
    '98': {'instruction': 'TYA', 'AMOD': 'impl'}}
